In [2]:
import nashpy as nash
import numpy as np

In [4]:
A = np.array([
    [8.39, 8.39, 8.39, 8.39],
    [8.96, 8.85, 8.65, 8.45],
    [9.95, 9.87, 9.6 , 9.2 ],
    [4.37, 5.11, 8.6 , 9.91],
])

B = np.array([
    [8.39, 8.96, 9.95, 4.37],
    [8.39, 8.85, 9.87, 5.11],
    [8.39, 8.65, 9.6,  8.6 ],
    [8.39, 8.45, 9.2,  9.91],
])

In [5]:
game = nash.Game(A, B)

In [19]:
tuple(game.lemke_howson_enumeration())

((array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 0., 1.]), array([0., 0., 0., 1.])),
 (array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 0., 1.]), array([0., 0., 0., 1.])))

In [20]:
tuple(game.support_enumeration())

((array([0., 0., 1., 0.]), array([0., 0., 1., 0.])),
 (array([0., 0., 0., 1.]), array([0., 0., 0., 1.])),
 (array([2.98447050e-17, 0.00000000e+00, 4.15204678e-01, 5.84795322e-01]),
  array([2.98447050e-17, 0.00000000e+00, 4.15204678e-01, 5.84795322e-01])))