In [1]:
import matplotlib.pyplot as plt
import nashpy as nash

import ambulance_game as abg

lambda_2 = 2
alpha = 0
target = 3.11

lambda_1_1 = 1
mu_1 = 1
num_of_servers_1 = 3
system_capacity_1 = 4
buffer_capacity_1 = 4

lambda_1_2 = 1
mu_2 = 1
num_of_servers_2 = 3
system_capacity_2 = 4
buffer_capacity_2 = 4

A, B, R = abg.game.get_payoff_matrices(
    lambda_2=lambda_2,
    lambda_1_1=lambda_1_1,
    lambda_1_2=lambda_1_2,
    mu_1=mu_1,
    mu_2=mu_2,
    num_of_servers_1=num_of_servers_1,
    num_of_servers_2=num_of_servers_2,
    system_capacity_1=system_capacity_1,
    system_capacity_2=system_capacity_2,
    buffer_capacity_1=buffer_capacity_1,
    buffer_capacity_2=buffer_capacity_2,
    target=target,
    alpha=alpha,
)
A += 1
B += 1

print("R = ", R)
print("A = ", A)
print("B = ", B)

game = nash.Game(A, B)
print("N.E. = ", tuple(game.support_enumeration()))


R =  [[0.5        0.06399852 0.         0.        ]
 [0.93600148 0.5        0.21457542 0.04051262]
 [1.         0.78542458 0.5        0.28609774]
 [1.         0.95948738 0.71390226 0.5       ]]
A =  [[0.99998394 0.99998394 0.99998394 0.99998394]
 [0.99998955 0.99998848 0.99998649 0.9999845 ]
 [0.99999952 0.9999987  0.99999596 0.99999199]
 [0.99994372 0.99995113 0.99998603 0.99999911]]
B =  [[0.99998394 0.99998955 0.99999952 0.99994372]
 [0.99998394 0.99998848 0.9999987  0.99995113]
 [0.99998394 0.99998649 0.99999596 0.99998603]
 [0.99998394 0.9999845  0.99999199 0.99999911]]
N.E. =  ((array([0., 0., 1., 0.]), array([0., 0., 1., 0.])), (array([0., 0., 0., 1.]), array([0., 0., 0., 1.])), (array([0.        , 0.        , 0.41775878, 0.58224122]), array([0.        , 0.        , 0.41775878, 0.58224122])))


In [20]:
100000 * (A - 0.9999)

array([[8.39356364, 8.39356364, 8.39356364, 8.39356364],
       [8.95516213, 8.84828864, 8.64909077, 8.44978331],
       [9.95232671, 9.87012397, 9.59602639, 9.19880488],
       [4.37175089, 5.11267151, 8.60282647, 9.91142703]])

In [19]:
100000 * (B - 0.9999)

array([[8.39356364, 8.95516213, 9.95232671, 4.37175089],
       [8.39356364, 8.84828864, 9.87012397, 5.11267151],
       [8.39356364, 8.64909077, 9.59602639, 8.60282647],
       [8.39356364, 8.44978331, 9.19880488, 9.91142703]])

In [22]:
import numpy as np

In [31]:
np.round(100000 * (B - 0.9999), 2)

array([[8.39, 8.96, 9.95, 4.37],
       [8.39, 8.85, 9.87, 5.11],
       [8.39, 8.65, 9.6 , 8.6 ],
       [8.39, 8.45, 9.2 , 9.91]])